language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang  
    - os: osx
      osx_image: xcode9.2
      compiler: clang
    - os: osx
      osx_image: xcode9.4
      compiler: clang

script:
  - brew audit --strict --online *.rb  # --new-formula is not ready because of coinutils.
  - rm /usr/local/include/c++ # https://github.com/Homebrew/brew/issues/1742#issuecomment-277308817
  - brew update
  - brew install dreal-deps/coinor/clp --build-from-source

notifications:
  email:
    recipients:
     - soonho.kong@gmail.com
